### ISSUE TITLE
Export constants

### ISSUE THREAD

**Issue by olliechick** [eBay/event-notification-nodejs-sdk#8]
The constants should be exported so they can be used when using this library, otherwise users have to declare them themselves (e.g. `'PRODUCTION'` to pass in to the `process` function).

**Comment by LokeshRishi** [comment]
I'm closing this issue as it has been inactive for a while. Please reopen, if you still need assistance.

**Comment by MickL** [comment]
Why would you close an issue just because it is inactive? Instead it would have been better if you actually fixed the issue.

In you example you use constants.js but this makes no sense because this only works because your example is in your repo. In the real world to use your constants they need to be exported so we can import them from 'event-notification-nodejs-sdk' package.
